param(
  [string]$Destination = ""
)

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName Microsoft.VisualBasic

function Choose-Folder {
  $dlg = New-Object System.Windows.Forms.FolderBrowserDialog
  $dlg.Description = "Chọn folder lưu toàn bộ file .afdesign"
  $dlg.ShowNewFolderButton = $true
  if ($dlg.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
    return $dlg.SelectedPath
  }
  return ""
}

function Safe-AsciiName([string]$title, [int]$index) {
  $base = $title -replace '\.(pdf|afdesign)$',''
  if ($base -match '(20\d{2}-\d{2}-\d{2}T\d{2}-\d{2}).*?(\d{10,}-\d{10,})') {
    return "$($matches[1])_$($matches[2]).afdesign"
  }
  if ($base -match '^\s*(\d{1,2})\s*[-_].*?(\d{10,}-\d{10,})') {
    return ("{0:D2}_{1}.afdesign" -f [int]$matches[1], $matches[2])
  }
  if ($base -match '(\d{10,}-\d{10,})') {
    return "$($matches[1]).afdesign"
  }
  return ("doc_{0:D2}.afdesign" -f $index)
}

if (-not $Destination) {
  $Destination = Choose-Folder
}
if (-not $Destination) { exit 0 }

# Pull document titles/count from the helper generated by Node.
$manifestPath = Join-Path $PSScriptRoot "open-docs-save-manifest.txt"
if (-not (Test-Path $manifestPath)) {
  Write-Host "Khong tim thay manifest document."
  exit 1
}

$docs = Get-Content -LiteralPath $manifestPath -Encoding UTF8 | Where-Object { $_.Trim() -ne "" }
if ($docs.Count -eq 0) {
  Write-Host "Khong co document dang mo."
  exit 1
}

$affinity = Get-Process | Where-Object {
  $_.MainWindowTitle -and ($_.ProcessName -match 'Affinity' -or $_.MainWindowTitle -match 'Affinity')
} | Select-Object -First 1

if (-not $affinity) {
  Write-Host "Khong tim thay cua so Affinity."
  exit 1
}

[Microsoft.VisualBasic.Interaction]::AppActivate($affinity.Id) | Out-Null
Start-Sleep -Milliseconds 700

Write-Host ""
Write-Host "SAVE ALL OPEN DOCS -> AFDESIGN (UI MODE)"
Write-Host "Folder: $Destination"
Write-Host "Documents: $($docs.Count)"
Write-Host "KHONG dung chuot/ban phim trong luc dang chay."
Write-Host ""

for ($i=0; $i -lt $docs.Count; $i++) {
  $title = [string]$docs[$i]
  $filename = Safe-AsciiName $title ($i+1)
  $target = Join-Path $Destination $filename

  # Save As
  [System.Windows.Forms.SendKeys]::SendWait("^+s")
  Start-Sleep -Milliseconds 900

  # In Windows Save As dialog, Ctrl+L focuses path/address in many dialogs.
  # More reliable: type full target into File name using Alt+N.
  [System.Windows.Forms.SendKeys]::SendWait("%n")
  Start-Sleep -Milliseconds 150
  [System.Windows.Forms.SendKeys]::SendWait("^a")
  [System.Windows.Forms.SendKeys]::SendWait($target.Replace("+","{+}").Replace("^","{^}").Replace("%","{%}").Replace("~","{~}").Replace("(","{(}").Replace(")","{)}").Replace("[","{[}").Replace("]","{]}"))
  [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
  Start-Sleep -Milliseconds 1000

  # Overwrite confirmation if target already exists.
  if (Test-Path -LiteralPath $target) {
    Start-Sleep -Milliseconds 250
  } else {
    # Dialog may still be asking overwrite / extension confirmation.
    [System.Windows.Forms.SendKeys]::SendWait("%y")
    Start-Sleep -Milliseconds 800
    [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
    Start-Sleep -Milliseconds 500
  }

  if (Test-Path -LiteralPath $target) {
    Write-Host ("[OK] " + $filename)
  } else {
    Write-Host ("[CHECK] " + $filename + " | file chua thay tren disk sau Save As")
  }

  if ($i -lt ($docs.Count-1)) {
    [System.Windows.Forms.SendKeys]::SendWait("^{TAB}")
    Start-Sleep -Milliseconds 350
  }
}
